# This file instructs Redocly's linter to ignore the rules contained for specific parts of your API.
# See https://redocly.com/docs/cli/ for more information.
specification/http/1.0/openapi.json:
  no-empty-servers:
    - '#/openapi'
  operation-4xx-response:
    - '#/paths/~1tools/get/responses'
